### PR TITLE
Mocking API call in number test.

### PR DESCRIPTION
**Pull request by incraigulous**
The number field API calls needed to be mocked to pass now that we added error testing. I also noticed the tests failed when a value wasn't set, so I set values to get the tests to pass.

### CODE REVIEW

**Comment by incraigulous** [comment]
Screenshot 2023-03-30 at 11 38 31 AM

@micahmills , I'm not sure why we're getting this error. I can run `npm install` and `npm ci` locally without issue.

**Comment by cairocoder01** [comment]
Sorry to interject a little late on this, but it seems like the number field now auto-saves to the API all the time. That would prevent it from being used on a standard form that would just submit the field normally (such as the magic links plugin). Shouldn't there be something to not use the API to save automatically if doesn't have an `apiRoot` property or something? That could help some of the testing issues as well so you don't have to mock HTTP requests.

**Comment by incraigulous** [comment]
@cairocoder01  should we close this out or modify it? You never know when we'll have a need for mocking, even if we aren't using the API, but I don't really see a use for it now.

**Comment by cairocoder01** [comment]
Mocking could be useful, but I say we close this out and just add it in when we really need it

**Pull request closed without merging**
