### PR TITLE
Changes for check duplicates, dt-tags and dt-connection

### PR DESCRIPTION
**Pull request by Vijenderrr**
@micahmills 
Added duplicate check function and changes for dt-tags and dt-connection .
Kindly provide your feedback for the same.
Thank You
@gp-birender @Ashima-Arora

### CODE REVIEW

**Review by micahmills — CHANGES_REQUESTED** [review]
Some of the changes here cause the existing tests to fail. run npm run test to see. Some of them are fixed by uncommenting line 212 of componentServices.js. 

It is possible that the test need to be updated to reflect the current changes, but lets double check that we aren't breaking anything unintentionally.

**Comment by Vijenderrr** [comment]
@micahmills 
Sure, we'll make sure not to impact anything and will update you if there are any issues.

**Comment by micahmills** [comment]
I made a couple of changes to account for the tests that were failing. moving the dt-tags case in the componentService.js back to line 193 fixes the remaining test, but I am not sure why were are moving it in the first place. If there is a reason to move it we can update the test, but I want to make sure because it could possible break things for people using the components if it is returning a different value than before

**Comment by micahmills** [comment]
@Vijenderrr  @Ashima-Arora @gp-birender I am going to go ahead and mere this in. The tags field is working on the new contact page, and the edit record page IF the tag field is empty. If a value is saved and the page is reloaded the component fails and doesn't load on the screen. You may have that fixed in an upcoming PR already.

**Comment by Ashima-Arora** [comment]
Hi @micahmills ,

We made a few changes related to this here in [another PR](https://github.com/DiscipleTools/disciple-tools-theme/pull/2510/files#diff-a6cf6ac104a9f97ffc7db281c1858721c10487200efbbc76cd4acfe74af75a96) at Line - 698 which needs to be merged to fix this tags not loading issue.
I am also adding a comment in that PR for your easy reference.

**What are we trying to achieve in that code?** 
We referred to the 'Develop' branch to see how **tags** work there. API there was working if we sent the object as 
image

and in the Next branch, the tags field wasn't visible on the Edit detail page. Moreover, if we are inspecting and searching for the same field, we get the reference as below screenshot, The DT-Tags field was loading in dom with incorrect structure in "Value" attribute. To fix this, we have made changes to Web components as well as **DT-Theme-> dt-core/global-functions.php**


image

Let us know your thoughts.

Thanks!

**Pull request merged**
