### PR TITLE
Rewrite api service and create componentService

### PR DESCRIPTION
**Pull request by cairocoder01**
add function to enable auto-save

@micahmills Take a look and let me know what you think. The thought is that we can include this on the details page in DT and just call `new ComponentService(...).enableAutoSave()`. It attaches a change event to all components on the page and sends API requests for each event. Needs to really be fleshed out and tested, but this is the general idea.

### CODE REVIEW

**Comment by micahmills** [comment]
I haven't had a chance to test this but I have read through it and it looks great.

Do we need to have a mechanism to make the autosave more fine grained. So we could have certain fields not autosave instead of enabling it on all fields? I am thinking of something like the comment field on a contact record. That text field only updates when you hit the comment button.

**Comment by cairocoder01** [comment]
That's a good point. The function could take an optional selector that
could be used to select which elements should be enabled.

**Comment by cairocoder01** [comment]
The way I have the change event separate, you could also just select elements manually and then attach that change event to whatever you want if there's a page more customized.

**Comment by cairocoder01** [comment]
@micahmills I've updated this with tests for `ComponentService.convertValue` to ensure we are converting the component values to what the API expects. Are you good with the direction of this that we could just merge this PR? We'll have to do further testing obviously, but it feels like it should work, right?

**Comment by micahmills** [comment]
I haven't been able to test the code but the read through I did looks good. Go ahead a merge it and we can go from there.

**Pull request merged**
